### PR TITLE
query(plan): add default expression validations

### LINKED ISSUE #4788: bug: create table default expression validation
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

ERROR 1105 (HY000): Code: 1006, displayText = Unable to get field named "CURRENT_TIMESTAMP". Valid fields: ["id"].

### How to Reproduce?

Table:
```
create table test1(id Int8, created timestamp  DEFAULT CURRENT_TIMESTAMP);

mysql> desc test1;
+---------+------------+------+-------------------+
| Field   | Type       | Null | Default           |
+---------+------------+------+-------------------+
| id      | Int8       | NO   | 0                 |
| created | DateTime32 | NO   | CURRENT_TIMESTAMP |
+---------+------------+------+-------------------+

```

Insert into:
```
mysql> insert into test1(id) values(1);
ERROR 1105 (HY000): Code: 1006, displayText = Unable to get field named "CURRENT_TIMESTAMP". Valid fields: ["id"].

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- Bug Fix
- Improvement
 

## Related Issues

Fixes #4788

### CODE REVIEW

File: common/planners/tests/it/plan_expression.rs [hunk 1]
```diff
@@ -91,7 +91,7 @@ fn test_expression_validate() -> Result<()> {
             desc: "today-not-pass",
             expression: Expression::ScalarFunction {
                 op: "today".to_string(),
-                args: vec![col("33")],
+                args: vec![col("a")],
```
Comment (Veeupup) [inline common/planners/tests/it/plan_expression.rs:94]: why we need to change this test?

Comment (sundy-li) [reply common/planners/tests/it/plan_expression.rs:94]: Because we do not have this col in schema.

**Review by Veeupup — APPROVED** [review]
