### PR TITLE
fix(query): fix pow and add strcmp domain

### LINKED ISSUE #14400: bug: numeric function POWER does not work
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

DatabendQuery v1.2.296-nightly-b9a4726b40(rust-1.75.0-nightly-2024-01-14T02:15:34.749419000Z)

### What's Wrong?

Screenshot 2024-01-22 at 12 29 11 AM

power

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Freejww**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

_fix pow function alias and add strcmp domain._

- fixes #14400 

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14418)

### CODE REVIEW

**Comment by sundy-li** [comment]
Please execute `env REGENERATE_GOLDENFILES=1 cargo test` in functions directory  to regenerate the tests

File: src/query/functions/src/scalars/arithmetic.rs [hunk 1]
```diff
@@ -77,6 +77,7 @@ pub fn register(registry: &mut FunctionRegistry) {
     registry.register_aliases("minus", &["subtract", "neg", "negate"]);
     registry.register_aliases("div", &["intdiv"]);
     registry.register_aliases("modulo", &["mod"]);
+    registry.register_aliases("pow", &["power"]);
```
Comment (sundy-li) [inline src/query/functions/src/scalars/arithmetic.rs:80]: Need tests to cover this change

**Review by sundy-li — APPROVED** [review]
