### PR TITLE
fix(query): handle empty LIKE ESCAPE in planner

### LINKED ISSUE #19562: `LIKE ... ESCAPE ''` panics in planner type checking
### Repro

```sql
SELECT 'a' LIKE 'a' ESCAPE '';
```

### Actual

The query fails with an internal panic:

```text
Code: 1104
called `Option::unwrap()` on a `None` value
```

Panic site:

- `src/query/sql/src/planner/semantic/type_check.rs:5378`

### Expected

Databend should reject an empty `ESCAPE` string with a normal SQL error, or define valid behavior for it. It must not panic during planning.

### Why this looks like the root cause

`resolve_like()` assumes the escape string has at least one character:

```rust
escape.chars().next().unwrap()
```

at:

- `src/query/sql/src/planner/semantic/type_check.rs:5375`
- `src/query/sql/src/planner/semantic/type_check.rs:5378`

When `escape == ""`, `next()` returns `None`, so the planner panics before returning a user-facing error.

### Impact

- `panic.log` shows this family occurred 2 times in one migration batch.
- Any generated or user-written query with `ESCAPE ''` can crash the planner path.

### Suggested fix direction

- Validate `ESCAPE` length before calling `convert_escape_pattern()`
- Return a semantic error for zero-length or multi-character escape strings

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- Fixes #19562
- Stop the planner LIKE fast path from unwrapping an empty `ESCAPE` string.
- Preserve existing operator/builtin fallback behavior by routing empty or non-single-character `ESCAPE` literals through the builtin `like` / `like_any` path instead of planner rewrites.
- Add planner and sqllogictest regressions for empty-escape bindings and backslash-containing fallback cases.

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

Validation:
- `cargo test -p databend-common-sql --test it planner -- --nocapture`
- `cargo test -p databend-common-sql --test it test_like_escape_preserves_existing_binding_semantics -- --nocapture`
- `cargo clippy -p databend-common-sql --test it -- -D warnings`
- `cargo fmt --all --check`

Logic test added for CI coverage:
- `tests/sqllogictests/suites/query/issues/issue_19562.test`

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19595)

### CODE REVIEW

**Comment by sundy-li** [comment]
Blocking issue in `resolve_like()`: this patch stops the panic for `ESCAPE `, but it also lets empty-escape patterns fall into the const/prefix fast paths even when those rewrites are not semantics-preserving.\n\nExample: `SELECT ax LIKE a\\x ESCAPE `. After this patch `new_like_str` is borrowed as `a\\x`, `check_const()` returns true, and the planner rewrites to equality against `a\\x`. The runtime LIKE matcher still treats backslash as escaping the next character, so that pattern behaves like `ax` and should return `true`, not `false`. The same issue applies to prefix rewrites like `a\\x%`.\n\nSo this changes the failure mode from a planner panic to silent wrong-answer plans for some empty-escape inputs. I think the safe options here are either to reject `ESCAPE ` with a normal SQL error, or to bypass the const/prefix rewrites when the escape string is present but empty.

File: src/query/sql/src/planner/semantic/type_check.rs [hunk 1]
```diff
@@ -5620,14 +5620,12 @@ impl<'a> TypeChecker<'a> {
...
-        let new_like_str = if let Some(escape) = escape {
-            Cow::Owned(convert_escape_pattern(
-                like_str,
-                escape.chars().next().unwrap(),
-            ))
-        } else {
-            Cow::Borrowed(like_str)
-        };
+        let new_like_str =
+            if let Some(escape_char) = escape.as_ref().and_then(|escape| escape.chars().next()) {
```
Comment (sundy-li) [inline src/query/sql/src/planner/semantic/type_check.rs]: This stops the panic, but it still treats ESCAPE '' as if the clause were omitted. That is still wrong for backslash patterns: for example, SELECT '%' LIKE '\\%' ESCAPE '' should not match once the escape character is disabled, but this path now falls through to the existing 3-arg like() behavior, which still interprets '\\' as the default escape. We need to either reject ESCAPE '' with a semantic error, or preserve the no-escape semantics consistently instead of routing it through the normal backslash-escape behavior.

**Comment by sundy-li** [comment]
Blocking: this patch removes the planner panic, but it still changes `LIKE ... ESCAPE '\` into incorrect execution semantics for backslash patterns.

`resolve_like()` now treats an empty escape string the same as no escape character, but the runtime matcher still hard-codes `\\` as a LIKE escape in `src/query/functions/src/scalars/comparison.rs` and `src/query/expression/src/filter/like.rs`. For example, `SELECT '%' LIKE '\\\\%' ESCAPE '\` will now bind and match as a literal percent, even though disabling the escape character should leave the backslash literal instead of escaping `%`.

This needs one of two fixes before merge:
1. preserve no-escape semantics in the runtime LIKE path when the third argument is empty, or
2. reject `ESCAPE '\` with a normal semantic error instead of routing it through the existing backslash-escape behavior.

**Comment by sundy-li** [comment]
Blocking issue: this patch fixes the panic, but it also turns previously accepted \ operator forms into semantic errors while the exposed 3-arg \ builtin still accepts an empty third argument as 'no escape'. Before this PR, non-fast-path cases reached \ and then the builtin, so queries such as \ could bind successfully. After this change they fail at bind time, which is a behavior regression and leaves the operator inconsistent with \ unless both paths are tightened together.

**Comment by sundy-li** [comment]
Blocking for review: this patch fixes the planner panic by rejecting `ESCAPE ''` everywhere in the operator path, but the public 3-arg `like()` builtin still accepts `''` as "no escape" in `src/query/functions/src/scalars/comparison.rs`.

That regresses previously bindable operator forms such as `SELECT 'a' LIKE concat('a') ESCAPE ''` and leaves `LIKE ... ESCAPE ''` inconsistent with `like(lhs, rhs, '')` unless the runtime/function semantics are tightened in the same change.

**Comment by sundy-li** [comment]
Blocking review note: `validate_like_escape()` now rejects `ESCAPE ''` for every operator path in `src/query/sql/src/planner/semantic/type_check.rs`, but the underlying LIKE builtins still accept an empty third argument.

`src/query/functions/src/scalars/comparison.rs` registers 3-arg `like` / `like_any`, defaults missing escapes to `""`, and `convert_escape_pattern()` keeps the raw pattern when the escape string is empty. That means `LIKE ... ESCAPE ''` now fails at bind time while the corresponding builtin form can still be expressed and executed with `''`.

Before this is safe to merge, the SQL surface needs one consistent rule: either tighten the builtin/runtime path in the same change, or preserve the existing non-panic operator behavior instead of rejecting only the operator syntax.

File: src/query/sql/src/planner/semantic/type_check.rs [hunk 2]
```diff
@@ -5682,6 +5690,29 @@ impl<'a> TypeChecker<'a> {
         self.resolve_function(span, name.as_str(), vec![], &arguments)
     }
 
+    fn validate_like_escape(span: Span, escape: &Option<String>) -> Result<Option<char>> {
```
Comment (sundy-li) [inline src/query/sql/src/planner/semantic/type_check.rs]: `validate_like_escape()` now rejects `ESCAPE ` on every operator path, but the builtin path still accepts an empty escape string. I verified this locally in the SQL integration harness on this branch: `SELECT a LIKE ANY (a) ESCAPE ` fails at bind time here, while `SELECT like_any(a, a, )` still binds successfully because `src/query/functions/src/scalars/comparison.rs` keeps treating an empty third argument as "no escape". That makes this a behavior regression and leaves two user-visible SQL surfaces inconsistent unless the builtin/runtime path is tightened in the same change.
