### PR TITLE
fix(query): make CSV quote_style unload-only

### LINKED ISSUE #17568: Feature: Quote Minimal for unloading CSV data
Currently when unloading CSV data, it is all quoted, e.g.
```
"email","name"
"",\N
"Anna","anna@something.com"
"Bill","bill@billsdomain.com"
```
With a quote_minimal option, it would only quote if instance of delimiter/field delimiter/quote/escape char appears within the field. Result:

```
email,name
,\N
Anna,anna@something.com
Bill,bill@billsdomain.com
```

### PR DESCRIPTION
**Pull request by KKould**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

Fixes #17568

Replace the CSV boolean `QUOTE_MINIMAL` option with an unload-only `QUOTE_STYLE` setting.

This PR supports two CSV output styles:

- `quote_not_null`: quote every non-NULL field
- `quote_minimal`: quote only when required by the CSV output format

`quote_style` now only controls unload behavior. It no longer depends on load-side options such as `empty_field_as`, `quoted_empty_field_as`, or `allow_quoted_nulls`, and `quote_minimal` no longer forces extra quotes for round-trip preservation.

This behavior has clear prior art in systems with similar CSV export semantics:

- PostgreSQL `COPY ... TO ... CSV` documents that values are quoted when they contain CSV-significant content such as the delimiter, quote character, NULL marker, or line breaks, and also provides `FORCE_QUOTE` to force quoting for selected columns: https://www.postgresql.org/docs/current/sql-copy.html
- DuckDB `COPY ... TO` exposes `FORCE_QUOTE`, which is the inverse control over the same quoting policy and implies default quote-only-when-needed CSV output: https://duckdb.org/docs/current/sql/statements/copy

## Changes

- replace the CSV `quote_minimal` bool with `quote_style` on `CsvFileFormatParams`
- support the two SQL values `quote_not_null` and `quote_minimal`
- rename the default quote style from `quote_all` to `quote_not_null` to match the actual NULL handling behavior
- persist `quote_style` through meta protobuf as a string field and update the v173 compatibility coverage
- make `quote_style` a pure unload-side setting by removing load-side option interactions from CSV field encoding
- update parser coverage, SHOW output expectations, and CSV sqllogictests to the new `quote_style` semantics

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

Validation:
- `cargo test -p databend-common-meta-app test_csv_quote_style_option -- --nocapture`
- `cargo test -p databend-common-proto-conv test_decode_v173_csv_quote_style -- --nocapture`
- `cargo test -p databend-common-formats --lib --no-run`
- `cargo fmt --all --check`

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19720)

### CODE REVIEW

File: src/meta/app/src/principal/file_format.rs [hunk 1]
```diff
@@ -263,6 +264,7 @@ impl FileFormatParams {
                 let nan_display = reader.take_string(OPT_NAN_DISPLAY, default.nan_display);
                 let escape = reader.take_string(OPT_ESCAPE, default.escape);
                 let quote = reader.take_string(OPT_QUOTE, default.quote);
+                let quote_minimal = reader.take_bool(OPT_QUOTE_MINIMAL, default.quote_minimal)?;
```
Comment (youngsofun) [inline src/meta/app/src/principal/file_format.rs]: need some research about the grammar, e.g.:

https://docs.rs/csv/latest/csv/enum.QuoteStyle.html
https://docs.python.org/3/library/csv.html#csv.QUOTE_ALL

Comment (KKould) [reply src/meta/app/src/principal/file_format.rs]: Currently, we referenced the syntax and functionality from Postgres and DuckDB, particularly FORCE_QUOTE. However, the current PR’s QUOTE_MINIMAL behaves in the opposite way. Since Postgres and DuckDB use minimal quoting by default, it may be worth discussing how to align with them. One possible approach is to support FORCE_QUOTE while making it enabled by default.

Comment (KKould) [reply src/meta/app/src/principal/file_format.rs]: The PR summary includes additional references to PG and DuckDB.

Comment (youngsofun) [reply src/meta/app/src/principal/file_format.rs]: @KKould Considering future expandability, perhaps `quote_style = <string>` would be better, unless we can demonstrate that only `quote_all` and `quote_minimal` are needed.

**Review by drmingdrmer — APPROVED** [review]
> @drmingdrmer partially reviewed 18 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/databend/19720)* status: 18 of 27 files reviewed, 2 unresolved discussions (waiting on KKould and sundy-li).

___
*[`src/meta/app/src/principal/file_format.rs` line 721 at r3](https://reviewable.io/reviews/databendlabs/databend/19720#-OqJwxXt4CZaMYkHQfhI:-OqJwxXt4CZaMYkHQfhJ:b-w36ols) ([raw file](https://github.com/databendlabs/databend/blob/89bacd0994904e7350a394313f3efa5a52715dec/src/meta/app/src/principal/file_format.rs#L721)):*
> ```XML
>     QuoteAll,
>     QuoteMinimal,
> }
> ```

always add documentation for a struct and its fields.



_Code quote:_
```XML
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum CsvQuoteStyle {
    #[default]
    QuoteAll,
    QuoteMinimal,
}
```

**Review by drmingdrmer — APPROVED** [review]
> @drmingdrmer reviewed 3 files and all commit messages.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/databend/19720)* status: 19 of 27 files reviewed, 2 unresolved discussions (waiting on KKould and sundy-li).

File: src/meta/app/src/principal/file_format.rs [hunk 2]
```diff
@@ -699,6 +713,46 @@ pub enum EmptyFieldAs {
     FieldDefault,
 }
 
+/// Controls how CSV values are quoted during output.
+#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
+#[serde(rename_all = "snake_case")]
+pub enum CsvQuoteStyle {
+    /// Quote every field in the CSV output.
+    #[default]
+    QuoteAll,
```
Comment (youngsofun) [inline src/meta/app/src/principal/file_format.rs]:
```suggestion
    QuoteNotNull,
```

https://docs.python.org/3/library/csv.html#csv.QUOTE_NOTNULL

File: src/query/formats/src/field_encoder/csv.rs [hunk 3]
```diff
@@ -69,6 +100,32 @@ pub fn write_csv_string(bytes: &[u8], buf: &mut Vec<u8>, quote: u8) {
     buf.push(quote);
 }
 
+fn csv_string_needs_quotes(bytes: &[u8], settings: &CsvQuoteSettings) -> bool {
+    if bytes.is_empty() {
```
Comment (youngsofun) [inline src/query/formats/src/field_encoder/csv.rs]: For each option, we must clearly define its scope of application:

1. Only for unload.
2. Only for load.
3. For both load and unload.

For example, regarding the quote style, in Rust CSV it is only used for unload because it only deals with strings. In Python CSV, it is used for both load and unload. Also, it is expected to handle null/empty values and even data types. 

Each quote style actually encompasses a set of behaviors. The problem is that there are too many combinations, which can get very complex. So for load, a series of orthogonal options such as `empty_field_as`, `quoted_empty_field_as`, `allow_quoted_nulls` are currently used for fine - grained control. 

Therefore, first of all, the quote style should only be used for unload and not be disrupted.
At the same time, I suggest that the quote style should not be affected by these parameters either, otherwise the behavior will be very difficult to describe clearly. 

The output quote style is not a strong requirement: in fact, it is sufficient for us to distinguish null values. We should only add it when there is a clear need. For example, the `minimal` style can reduce the file size, and in some cases, it may be necessary to distinguish data types (but this does not conform to the standard, such as reading with Python's `csv.QUOTE_NONNUMERIC/csv.QUOTE_STRINGS`).

Even if more options are added in the future, there is no need to worry, because compared with load, the behavior of unload is easier to describe.

File: src/query/formats/src/field_encoder/csv.rs [hunk 4]
```diff
@@ -31,15 +33,44 @@ use crate::field_encoder::FieldEncoderBytes;
...
+
+impl CsvQuoteSettings {
+    pub fn from_params(params: &CsvFileFormatParams) -> Self {
+        Self {
+            quote_char: params.quote.as_bytes()[0],
+            quote_style: params.quote_style,
+            field_delimiter: params.field_delimiter.as_bytes()[0],
+            record_delimiter: params.record_delimiter.as_bytes().to_vec(),
+            escape_char: params.escape.as_bytes().first().copied(),
+            null_bytes: params.null_display.as_bytes().to_vec(),
```
Comment (youngsofun) [inline src/query/formats/src/field_encoder/csv.rs]: so the last for fields should not get involved.

null is outputted outside already so  null_bytes is not needed too.

File: src/query/formats/src/field_encoder/csv.rs [hunk 5]
```diff
@@ -69,6 +91,23 @@ pub fn write_csv_string(bytes: &[u8], buf: &mut Vec<u8>, quote: u8) {
     buf.push(quote);
 }
 
+fn csv_string_needs_quotes(bytes: &[u8], settings: &CsvQuoteSettings) -> bool {
+    bytes.iter().any(|byte| {
+        *byte == settings.quote_char
+            || *byte == settings.field_delimiter
+            || settings.record_delimiter.contains(byte)
```
Comment (youngsofun) [inline src/query/formats/src/field_encoder/csv.rs]:
```suggestion
            || settings.record_delimiter[0] == *byte
```
