### PR TITLE
fix: rename PanicError and fix executor OOM mapping

### LINKED ISSUE #19612: Rename ErrorCode::PanicError to reduce confusion and fix misuse
**Summary**

                                                                                                                     
                                                                  
  ErrorCode::PanicError (code 1104) has two problems:                                                                             
                                                                  
  1. The name is misleading. When users or operators see PanicError in logs or error responses, the natural reaction is "the      
  server panicked" — which implies a serious bug or crash. In reality, this error code represents a caught and recovered panic
  (via catch_unwind), not an ongoing crash. The process is still alive and functioning normally.                                  
  2. It's being misused for non-panic scenarios. Two call sites in the pipeline executor use PanicError to report memory
  out-of-limit errors, which have nothing to do with panics:                                                                      
    - src/query/service/src/pipelines/executor/executor_graph.rs:453
    - src/query/service/src/pipelines/executor/executor_worker_context.rs:207                                                     
                                                                                                                                  
  Proposed Changes                                                                                                                
                                                                                                                                  
  1. Rename PanicError → UnwindError (or CaughtPanic / TaskPanicked). The new name should convey that a panic was caught and      
  converted into an error, not that the system is in an undefined state.
  2. Fix the two misuse sites in the pipeline executor. The memory out-of-limit errors should use a more appropriate error code   
  (e.g., AbortedQuery or a dedicated memory-limit error code) instead of PanicError.                                              
  3. The error code number 1104 should remain unchanged for backward compatibility.

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

Fixes #19612.

Rename `ErrorCode::PanicError` to `ErrorCode::UnwindError` while keeping error code `1104`, and stop using that code for memory-limit flush failures in the pipeline executor.

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19614)

### CODE REVIEW

File: src/query/service/src/pipelines/executor/executor_worker_context.rs [hunk 1]
```diff
@@ -39,6 +39,10 @@ use crate::pipelines::executor::WorkersCondvar;
 use crate::pipelines::executor::executor_graph::ProcessorWrapper;
 use crate::pipelines::executor::processor_async_task::ExecutorTasksQueue;
 
+pub(super) fn out_of_limit_error(error: impl Debug) -> ErrorCode {
+    ErrorCode::AbortedQuery(format!("{error:?}"))
```
Comment (zhang2014) [inline src/query/service/src/pipelines/executor/executor_worker_context.rs]: Please do not use `AbortedQuery`; it has a special meaning in the executor.

Comment (sundy-li) [inline src/query/service/src/pipelines/executor/executor_worker_context.rs]: Mapping executor OOM flush failures to `AbortedQuery` changes executor semantics, not just user-facing wording. In this stack, `ABORTED_QUERY` is already the sentinel for explicit cancellation/timeout paths, and parts of the executor treat it specially. Please use a non-abort error code here (or add a dedicated memory-limit code) instead of reusing the cancellation code.
