### PR TITLE
fix(parser): preserve detailed stage URI errors

### LINKED ISSUE #10966: improve error message when create stage
**Summary**

Description for this feature.

```
bendsql :) create stage mystage url='/Users/yangxiufeng/work/databend/test' file_format=(type=csv);
Code: 1005, Text = error: 
  --> SQL:1:66
  |
1 | create stage mystage url='/Users/yangxiufeng/work/databend/test' file_format=(type=csv);
  |                                                                  ^^^^^^^^^^^ expected `CONNECTION`, `CREDENTIALS`, or `LOCATION_PREFIX`

```

here I miss "fs://" in the  url

### PR DESCRIPTION
**Pull request by KKould**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- fixes #10966 and #13811 by preserving detailed URI parsing errors for `CREATE STAGE`
- return actionable parser errors for local filesystem paths like `/tmp/` and `file:///tmp/`
- stop collapsing malformed external URIs such as `s3://bucket:abc/path/` into a generic `invalid uri`

## Changes

- add targeted URI hints in `UriLocation::from_uri` for local filesystem path misuse
- preserve the concrete `ParseError` message when stage URL parsing fails instead of replacing it with a generic parser error
- simplify parser error handling to use a single `ErrorKind::Other(String)` path via `ErrorKind::other(...)`
- add parser regression coverage for `/path`, `file:///path`, and malformed `s3://...` stage URLs
- add sqllogictest coverage for the local filesystem path guidance

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

Validation run locally:

```bash
cargo test -p databend-common-ast parser -- --nocapture
```

Added logic-test coverage in `tests/sqllogictests/suites/stage/prefix.test`, but did not run `databend-sqllogictests` locally because it requires a running local query service environment.

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19746)

### CODE REVIEW

File: src/query/ast/src/ast/statements/copy.rs [hunk 1]
```diff
@@ -520,6 +520,18 @@ pub struct UriLocation {
 }
 
 impl UriLocation {
+    fn invalid_uri_hint(uri: &str) -> Option<&'static str> {
+        if uri.starts_with('/') {
+            Some("local filesystem paths must use fs:///path/ instead of /path/")
+        } else if uri.starts_with("file://") {
```
Comment (sundy-li) [inline src/query/ast/src/ast/statements/copy.rs:526]: Both `file://` and `fs://`should be ok I think.

Comment (KKould) [reply src/query/ast/src/ast/statements/copy.rs:526]: `file://` exists in some other code paths, but `CREATE STAGE` currently only supports local paths through `fs:///...` in the stage/storage binder path. So this PR keeps behavior unchanged and only improves the error message. If we want to accept `file://` for stage URLs too, that should be a separate change.

Comment (KKould) [reply src/query/ast/src/ast/statements/copy.rs:526]: ref: 
- https://github.com/databendlabs/databend/blob/main/src/query/sql/src/planner/binder/location.rs#L568
- https://github.com/databendlabs/databend/blob/main/src/query/sql/src/planner/binder/location.rs#L597

**Review by sundy-li — APPROVED** [review]
