### PR TITLE
fix(query): support IF NOT EXISTS for ALTER TABLE ADD COLUMN

### LINKED ISSUE #19611: bug: ALTER TABLE ADD COLUMN should support IF NOT EXISTS
## Summary

`ALTER TABLE ... ADD COLUMN` currently does not support `IF NOT EXISTS`.

## Reproduction

```sql
ALTER TABLE runs ADD COLUMN IF NOT EXISTS kind VARCHAR NOT NULL DEFAULT 'user_turn' COMMENT 'user_turn | session_checkpoint';
```

## Actual Behavior

```text
SyntaxError(1005): Unexpected reserved keyword "NOT". Expecting a data type after column name "kind".
```

## Expected Behavior

`ALTER TABLE ... ADD COLUMN IF NOT EXISTS` should be accepted. If the column already exists, the statement should succeed without error.

## Notes

This affects compatibility with common SQL dialect behavior for idempotent schema migrations.

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- add parser support for `ALTER TABLE ... ADD COLUMN IF NOT EXISTS`
- make duplicate add-column requests a no-op when `IF NOT EXISTS` is present
- add Rust and SQL regressions for the new idempotent DDL behavior

## Changes

1. Extended the ALTER TABLE add-column AST, display formatting, and parser grammar with an `if_not_exists` flag.
2. Threaded the new flag through the add-column plan in the SQL binder.
3. Short-circuited binder/interpreter execution when the target column already exists and `IF NOT EXISTS` is specified.
4. Added AST parser coverage, a fuse storage integration test, and a sqllogictest regression.

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - Pair with the reviewer to explain why

Validation commands:

```bash
cargo test -p databend-common-ast --test it parser::test_statement -- --exact
cargo test -p databend-query --test it add_column_if_not_exists -- --nocapture
cargo clippy -p databend-common-sql --lib -- -D warnings
cargo clippy -p databend-common-ast --test it -- -D warnings
```

## Type of change

- [x] Bug fix

Fixes #19611

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19615)

### CODE REVIEW

File: src/query/service/src/interpreters/interpreter_table_add_column.rs [hunk 1]
```diff
@@ -103,6 +103,15 @@ impl Interpreter for AddTableColumnInterpreter {
                 &self.plan.database, &self.plan.table
             )));
         }
+        if self.plan.if_not_exists
```
Comment (sundy-li) [inline src/query/service/src/interpreters/interpreter_table_add_column.rs]: This early return skips the later `AddColumnOption::After(name)` validation. With this change, `ALTER TABLE ... ADD COLUMN IF NOT EXISTS existing_col ... AFTER missing_col` will now succeed silently instead of reporting that the anchor column is missing, because the duplicate-column no-op triggers before `schema.index_of(name)?`. Please keep the no-op semantics, but only after validating the requested placement clause.

**Comment by sundy-li** [comment]
ci check is failed, please fix the check

File: src/query/service/src/interpreters/interpreter_table_add_column.rs [hunk 2]
```diff
@@ -132,6 +131,15 @@ impl Interpreter for AddTableColumnInterpreter {
             AddColumnOption::After(name) => table_info.meta.schema.index_of(name)? + 1,
             AddColumnOption::End => table_info.meta.schema.num_fields(),
         };
+        if self.plan.if_not_exists
```
Comment (sundy-li) [inline src/query/service/src/interpreters/interpreter_table_add_column.rs]: `IF NOT EXISTS` is supposed to make duplicate add-column requests a no-op, but the duplicate check runs after the `nextval` / `AUTOINCREMENT` validations. If the column already exists on a non-empty table, `ALTER TABLE ... ADD COLUMN IF NOT EXISTS existing_col ... AUTOINCREMENT` (or `DEFAULT nextval(...)`) will still fail here instead of returning success. The existence short-circuit needs to happen before validations that are only relevant when we are actually adding a new column.

File: src/query/sql/src/planner/binder/ddl/table.rs [hunk 3]
```diff
@@ -1163,7 +1164,7 @@ impl Binder {
                     .await?
                     .schema();
                 let (field, comment, is_deterministic, is_nextval, is_autoincrement) =
-                    self.analyze_add_column(column, schema).await?;
+                    self.analyze_add_column(column, schema.clone()).await?;
```
Comment (sundy-li) [inline src/query/sql/src/planner/binder/ddl/table.rs:1169]: `IF NOT EXISTS` still does full binder-side validation before the duplicate no-op path in the interpreter can fire. For an existing column, statements like `ALTER TABLE t ADD COLUMN IF NOT EXISTS b STRING AUTOINCREMENT ORDER` (or any invalid default/computed expression) will still fail here in `analyze_add_column(...)` instead of being treated as an idempotent no-op. That means the implementation only suppresses interpreter-time errors, not binder-time ones. Can we move the duplicate check ahead of `analyze_add_column`, or otherwise bypass binder validation when the target column already exists?
