### PR TITLE
fix(query): avoid SHOW TABLES refresh failures

### LINKED ISSUE #14607: Bug: failed to SHOW TABLES in default database
**Summary**

it displays one warning in the response:

```
    "warnings": [
        "Failed to list tables in database: default, StoragePermissionDenied. Code: 3002, Text = PermissionDenied (persistent) at stat, context: { uri: https://s3.us-east-2.amazonaws.com/databend-toronto/1/402/last_snapshot_location_hint, response: Parts { status: 403, version: HTTP/1.1, headers: {\"x-amz-request-id\": \"C4WQ503JKHKM9KRB\", \"x-amz-id-2\": \"YAQ1bX3P/qP6nezU7hVKhovEPAyKcCg7ZcuRjX+NY6wi/YUyB8EW2VWy655eHMeoDZjDzI41P3I=\", \"content-type\": \"application/xml\", \"date\": \"Mon, 05 Feb 2024 09:15:19 GMT\", \"server\": \"AmazonS3\"} }, service: s3, path: 1/402/last_snapshot_location_hint }."
    ],```

it turns out there is a S3 access when executing `SHOW TABLES`, but we can not find out which table is bad in this warning.

### PR DESCRIPTION
**Pull request by KKould**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- fix `SHOW TABLES` for attached tables whose snapshot-hint refresh would fail with object-storage permission errors
- keep the `disable_table_info_refresh()` behavior when `system.tables` re-fetches a filtered catalog
- add a regression test covering the broken attached-table refresh path

- fixes: #14607

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

Validation:

- `cargo test -p databend-query --test it test_show_tables_ignores_broken_attached_table_refresh -- --nocapture`
- `cargo fmt --all --check`

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19759)

### CODE REVIEW

File: src/query/storages/system/src/tables_table.rs [hunk 1]
```diff
@@ -676,7 +676,7 @@ where TablesTable<WITH_HISTORY, WITHOUT_VIEW>: HistoryAware
             let mut res = vec![];
             for name in &catalog_name {
                 if *name == ctl_name {
-                    let ctl = ctx.get_catalog(name).await?;
+                    let ctl = ctx.get_catalog(name).await?.disable_table_info_refresh()?;
```
Comment (TCeason) [inline src/query/storages/system/src/tables_table.rs]:
```rust
  let ctls = if !catalog_name.is_empty() {                                                                                                                                                                   
      if catalog_name.iter().any(|name| *name == ctl_name) {                                                                                                                                                 
          vec![(ctl_name, catalog_impl)]                                                                                                                                                                     
      } else {                                                                                                                                                                                               
          vec![]                                                                                                                                                                                             
      }                                                                                                                                                                                                      
  } else {                                                        
      vec![(ctl_name, catalog_impl)]                                                                                                                                                                         
  };                                                                                                                                                                                                         
```

**Review by TCeason — CHANGES_REQUESTED** [review]

**Review by TCeason — APPROVED** [review]
