### PR TITLE
fix(storage): inflated block size estimation caused by shared string buffers

### LINKED ISSUE #19658: bug: inflated block size estimation caused by shared string buffers
```sql
root@localhost:8000/default/default> create or replace table t (
  id int,
  k int,
  s string
) cluster by(k);

root@localhost:8000/default/default> insert into t
select
  number as id,
  number % 10 as k,
  repeat('x', 500000) as s
from numbers(2000);
╭─────────────────────────╮
│ number of rows inserted │
│          UInt64         │
├─────────────────────────┤
│                    2000 │
╰─────────────────────────╯
2000 rows written in 2.058 sec. Processed 2 thousand rows, 535.89 KiB (971.82 rows/s, 260.39 KiB/s)

root@localhost:8000/default/default> insert into t
select
  2000 + number as id,
  number % 10 as k,
  concat('small_', number::string) as s
from numbers(200);
╭─────────────────────────╮
│ number of rows inserted │
│          UInt64         │
├─────────────────────────┤
│                     200 │
╰─────────────────────────╯
200 rows written in 0.241 sec. Processed 200 rows, 4.76 KiB (829.88 rows/s, 19.75 KiB/s)

root@localhost:8000/default/default> alter table t recluster final;
2200 rows written in 3.705 sec. Processed 2.2 thousand rows, 8.38 GiB (593.79 rows/s, 2.26 GiB/s)

root@localhost:8000/default/default> select snapshot_id, block_count, row_count,bytes_uncompressed,bytes_compressed from fuse_snapshot('default','t') limit 2;
╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
│            snapshot_id           │ block_count │ row_count │ bytes_uncompressed │ bytes_compressed │
│              String              │    UInt64   │   UInt64  │       UInt64       │      UInt64      │
├──────────────────────────────────┼─────────────┼───────────┼────────────────────┼──────────────────┤
│ 019d4d268c9e769b9aa38c770bf345e5 │           9 │      2200 │         9000053646 │            43160 │
│ 019d4d26793377e5b05e19a6369e437d │           2 │      2200 │             553625 │             6548 │
╰────────────────────────────────────────────────────────────────────────────────────────────────────╯
2 rows read in 0.041 sec. Processed 2 rows, 539 B (48.78 rows/s, 12.84 KiB/s)
```

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

This PR fixes block size estimation for variable-length data in two places:

  1. `DataBlock::estimate_block_size()` now uses the **GC-aware memory size** path, so block statistics reflect the effective column footprint after compaction instead of inflated shared-buffer memory.
  2. `estimated_scalar_repeat_size()` is **corrected** for const variable-length values, so repeated String / Array / Map scalars are no longer underestimated compared with materialized columns.

  It addresses two issues:
  1. `estimated_scalar_repeat_size()` could significantly underestimate const variable-length values.
  2. `estimate_block_size()` used a non-GC memory size path, which could overestimate block size for view-backed columns.

  Together, these changes make block_size and bytes_uncompressed more stable across insert, recluster, and readback.

After fix
```sql
root@localhost:8000/default/default> create or replace table t (
  id int,
  k int,
  s string
) cluster by(k);

root@localhost:8000/default/default> insert into t
select
  number as id,
  number % 10 as k,
  repeat('x', 500000) as s
from numbers(2000);
╭─────────────────────────╮
│ number of rows inserted │
│          UInt64         │
├─────────────────────────┤
│                    2000 │
╰─────────────────────────╯
2000 rows written in 2.576 sec. Processed 2 thousand rows, 953.72 MiB (776.4 rows/s, 370.23 MiB/s)

root@localhost:8000/default/default> insert into t
select
  2000 + number as id,
  number % 10 as k,
  concat('small_', number::string) as s
from numbers(200);
╭─────────────────────────╮
│ number of rows inserted │
│          UInt64         │
├─────────────────────────┤
│                     200 │
╰─────────────────────────╯
200 rows written in 0.154 sec. Processed 200 rows, 6.41 KiB (1.3 thousand rows/s, 41.63 KiB/s)

root@localhost:8000/default/default> alter table t recluster final;
2200 rows written in 4.720 sec. Processed 2.2 thousand rows, 953.73 MiB (466.1 rows/s, 202.06 MiB/s)

root@localhost:8000/default/default> select snapshot_id, block_count, row_count,bytes_uncompressed,bytes_compressed from fuse_snapshot('default','t') limit 2;

╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
│            snapshot_id           │ block_count │ row_count │ bytes_uncompressed │ bytes_compressed │
│              String              │    UInt64   │   UInt64  │       UInt64       │      UInt64      │
├──────────────────────────────────┼─────────────┼───────────┼────────────────────┼──────────────────┤
│ 019d4d39b6a57f9aa6feb8f1d9b9519b │           9 │      2200 │         1000055336 │            19265 │
│ 019d4d399a887e52b7cb4b1a3358a21a │          10 │      2200 │         1000055330 │            13501 │
╰────────────────────────────────────────────────────────────────────────────────────────────────────╯
2 rows read in 0.055 sec. Processed 2 rows, 539 B (36.36 rows/s, 9.57 KiB/s)
```

Fixes #19658

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19657)

### CODE REVIEW

**Comment by zhyass** [comment]
@codex review

File: src/query/expression/src/block.rs [hunk 1]
```diff
@@ -991,7 +991,7 @@ impl DataBlock {
                 BlockEntry::Const(s, data_type, _) => {
                     s.as_ref().estimated_scalar_repeat_size(num_rows, data_type)
                 }
-                _ => entry.memory_size(),
+                _ => entry.memory_size_with_options(true),
```
Comment (youngsofun) [inline src/query/expression/src/block.rs:994]: This will be significantly slower; make sure this function is only called when necessary.
