### PR TITLE
fix(query): unsupport datetime format item should not return panic error

### LINKED ISSUE #17318: Bug: `date_format` function with invalid `format` argument panic
### Search before asking

- [x] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

`date_format` function with invalid `format` argument panic, seems caused by `chrono` bug
this bug is found by Tidb test
```
panicked at /home/b41sh/.rustup/toolchains/nightly-2024-11-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2688:14:
a Display implementation returned an error unexpectedly: Error
   0: backtrace::backtrace::libunwind::trace
             at /home/b41sh/.cargo/git/checkouts/backtrace-rs-fb1f822361417489/72265be/src/backtrace/libunwind.rs:116:5
      backtrace::backtrace::trace_unsynchronized
             at /home/b41sh/.cargo/git/checkouts/backtrace-rs-fb1f822361417489/72265be/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
```

### How to Reproduce?

```sql
root@0.0.0.0:48000/default> SELECT date_format(now(), '%i');
error: APIError: QueryFailed: [1104]a Display implementation returned an error unexpectedly: Error

root@0.0.0.0:48000/default> SELECT date_format(now(), '%O');
error: APIError: QueryFailed: [1104]a Display implementation returned an error unexpectedly: Error
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

unsupport datetime format item should not return panic error

- fix #17318

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/17323)

### CODE REVIEW

File: src/query/functions/src/scalars/timestamp/src/datetime.rs [hunk 1]
```diff
@@ -700,18 +701,29 @@ fn register_to_string(registry: &mut FunctionRegistry) {
...
                     // https://github.com/BurntSushi/jiff/issues/155
-                    // ASCII is currently required in jiff crate
-                    let res = ts.format(format).to_string();
-                    output.push(&res);
+                    // Consider use jiff crate 0.1.24 version.
+                    // let datetime = micros.to_timestamp(ctx.func_ctx.jiff_tz.clone());
+                    // match strtime::format(&datetime, format) {
+                    //     Ok(res) => output.push(&res),
+                    //     Err(e) => { ctx.set_error(output.len(), e.into());output.push_null() },
+                    // }
```
Comment (b41sh) [inline src/query/functions/src/scalars/timestamp/src/datetime.rs:710]: this comment code seems useless, we can delete them.

Comment (TCeason) [reply src/query/functions/src/scalars/timestamp/src/datetime.rs:710]: Yes. better to convert as an issue.

**Review by b41sh — APPROVED** [review]
