### PR TITLE
fix(query): handle database ID properly in columns table permission check

### LINKED ISSUE #18797: bug: user with DB OWNERSHIP and query system.columns no assign db return empty result
**Summary**

bendsql
```
drop user if exists a;
drop role if exists role1;
drop database if exists sysdb;
create user a identified by '123' with default_role='role1';
create role role1;
grant role role1 to a;
create database sysdb;
create table sysdb.t(id int);
grant ownership on sysdb.* to role role1;
grant ownership on sysdb.t to role role1;
```

bendsql -ua -p123

```
-- should return result but empty.
select * from system.columns where table='t';
```

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

In main the code didn't properly handle db_id_opt from dbs_in_default_catalog, causing incorrect permission filtering for system.columns table queries.

This fix:
- Collects both database names and IDs from visibility checker
- Uses mget_database_names_by_ids to resolve missing names
- Properly filters databases with both name and ID information
- Fixes with column privilege checking

Fixes #18797

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/18798)

### CODE REVIEW

File: src/query/storages/system/src/columns_table.rs [hunk 1]
```diff
@@ -317,43 +317,61 @@ pub(crate) async fn dump_tables(
...
+                        if let Some(db_name) = db_name_opt {
+                            name_set.insert(db_name.to_string());
+                        }
+                        if let Some(db_id) = db_id_opt {
+                            id_list.push(**db_id);
+                        }
+                    }
+
+                    let db_names = catalog
+                        .mget_database_names_by_ids(&tenant, &id_list)
```
Comment (sundy-li) [inline src/query/storages/system/src/columns_table.rs:350]: if `id_list` is a large vector, will it lead too many calls to meta service?

Comment (TCeason) [reply src/query/storages/system/src/columns_table.rs:350]: No. mget has a chunk size. default is `CHUNK_SIZE: usize = 256;`.

And at present, the number of databases in known systems is less than 10,000.

**Review by sundy-li — APPROVED** [review]
