### PR TITLE
fix(query): handle repeated % in LIKE folding

### LINKED ISSUE #19561: `LIKE` constant folding panics on patterns with repeated `%`
### Repro

```sql
SELECT 'ababac' LIKE 'abab%%%%%';
```

### Actual

The query fails with an internal panic:

```text
Code: 1104
assertion failed: segments_len > 1
```

Panic site:

- `src/query/expression/src/filter/like.rs:144`

### Expected

Databend should either:

- normalize redundant `%` and return the correct boolean result, or
- return a regular SQL error

It must not panic.

### Why this looks like the root cause

`TypeChecker::resolve_like()` can route constant `LIKE` expressions into constant folding, which eventually evaluates `LikePattern::simple_pattern()`. That function contains:

```rust
debug_assert!(segments_len > 1);
```

at:

- `src/query/expression/src/filter/like.rs:144`

Repeated `%` can collapse the pattern into too few segments, violating that assumption and triggering the panic.

### Impact

- `panic.log` shows this happened 7 times in one migration batch.
- It blocks automatic conversion of DuckDB `LIKE` coverage and turns a deterministic SQL case into an internal error.

### Suggested fix direction

- Normalize repeated `%` before building `LikePattern`, or
- make `simple_pattern()` handle `segments_len <= 1` safely instead of asserting

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- fixes #19561
- handle `LIKE` simple patterns that collapse to zero or one literal segment when repeated `%` is constant-folded
- add unit and sqllogictest regressions for repeated `%` patterns

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

## Validation

- `cargo test -p databend-common-expression`
- `cargo clippy -p databend-common-expression --lib --tests -- -D warnings`
- `cargo fmt --all --check`
- Added sqllogictest coverage in `tests/sqllogictests/suites/query/functions/02_0005_function_compare.test` (not run locally in this environment)

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/19590)

### CODE REVIEW

File: src/query/expression/src/filter/like.rs [hunk 1]
```diff
@@ -135,11 +135,28 @@ impl LikePattern<'_> {
...
+            0 => return true,
+            // Repeated '%' can also collapse to a single concrete segment, which is
+            // equivalent to one of the simpler LIKE variants.
+            1 => {
+                let segment = &segments[0];
+                return match (has_start_percent, has_end_percent) {
+                    (false, false) => haystack == segment,
+                    (true, false) => haystack.ends_with(segment),
+                    (false, true) => haystack.starts_with(segment),
+                    (true, true) => find(haystack, segment).is_some(),
```
Comment (sundy-li) [inline src/query/expression/src/filter/like.rs:150]: This fixes the panic for string LIKE, but it still leaves repeated leading/trailing `%` patterns as `SimplePattern`. That changes VARIANT semantics because `variant_vectorize_like_jsonb()` treats `SimplePattern` differently from `StartOfPercent`/`EndOfPercent`: for example, `parse_json({name:abab}) like %abab` is false today, while `parse_json({name:abab}) like %%%%abab` will become true by traversing nested strings. Redundant `%` should not change the result. Can we normalize the one-segment cases back to the existing simpler variants, or handle equivalent one-segment `SimplePattern`s the same way in the VARIANT path?

Comment (sundy-li) [reply src/query/expression/src/filter/like.rs:150]: Normalized the repeated-`%` one-segment cases in `generate_like_pattern()`, so they now collapse back to `Constant` / `OrdinalStr` / `StartOfPercent` / `EndOfPercent` / `SurroundByPercent` instead of staying as `SimplePattern`. That keeps `variant_vectorize_like_jsonb()` on the same dispatch path as the non-redundant pattern. Added a VARIANT unit test for `%abab` vs `%%%%abab` and `abab%` vs `abab%%%%`, plus sqllogictest coverage in `query/filter.test`.

File: tests/sqllogictests/suites/query/functions/02_0005_function_compare.test [hunk 2]
```diff
@@ -161,6 +161,21 @@ select 'a%b_c\d' like 'a!%b!_c!\\d' escape '!'
 ----
 1
 
+query B
+select 'ababac' like 'abab%%%%%'
```
Comment (sundy-li) [inline tests/sqllogictests/suites/query/functions/02_0005_function_compare.test:165]: This added regression is still red on the PR head. In CI run 23498244372, `select ababac like abab%%%%%` returned `0` instead of `1` at this line, so the end-to-end SQL `LIKE` path is still incorrect even though the new unit tests pass. The patch needs to cover the query execution/planner path too, not just `generate_like_pattern` in isolation.

**Comment by sundy-li** [comment]
Blocking issue from review: the PR head still fails its own new sqllogictest in the real query path. CI run 23498244372 reports `select ababac like abab%%%%%` as `0` instead of `1` at `tests/sqllogictests/suites/query/functions/02_0005_function_compare.test:164`. The new unit tests around `generate_like_pattern` pass, but the SQL `LIKE` operator is still incorrect end-to-end for this case.

**Comment by sundy-li** [comment]
Blocking issue: `normalize_simple_pattern()` now classifies `abab%%%%%` as `LikePattern::EndOfPercent(_)`, but `calc_like_domain()` still removes only one trailing `%`. Constant folding therefore compares the left prefix against `abab%%%%` instead of `abab`, so expressions like `ababac LIKE abab%%%%%` get folded to `false` even though the runtime LIKE matcher returns `true`. This is why the new sqllogictest still fails end-to-end.

**Comment by sundy-li** [comment]
`generate_like_pattern()` now normalizes `abab%%%%%` to `LikePattern::EndOfPercent("abab")`, but `calc_like_domain()` still derives the prefix from the raw pattern string and only strips a single trailing `%`. That makes the constant folder mis-fold `select ababac like abab%%%%%` to `0`, which matches the failing sqllogictest jobs on the PR head.\n\n`calc_like_domain()` needs to derive the prefix from the normalized `LikePattern::EndOfPercent(v)` (or otherwise collapse repeated trailing `%` there) so the planner and runtime agree on repeated-`%` patterns.

**Comment by sundy-li** [comment]
Confirmed blocker: repeated trailing `%` is normalized in `generate_like_pattern()`, but `calc_like_domain()` still builds its prefix from the raw pattern and only strips a single trailing `%`. That keeps planner/domain folding inconsistent with runtime LIKE evaluation for literals such as `abab%%%%%`, which matches the failing query sqllogic jobs on the PR head.

This needs a matching update in `src/query/functions/src/scalars/comparison.rs` so the folded prefix comes from the normalized `LikePattern::EndOfPercent(v)` (or otherwise collapses repeated trailing `%`) before this can be approved.

**Comment by sundy-li** [comment]
Blocking issue on current head: `generate_like_pattern()` now normalizes repeated trailing `%` into `LikePattern::EndOfPercent(_)`, but `calc_like_domain()` in `src/query/functions/src/scalars/comparison.rs` still derives its prefix from the raw pattern string and only removes one trailing `%`.

That keeps planner/domain folding inconsistent with runtime LIKE evaluation for literals such as `abab%%%%%`. A query like `SELECT ababac LIKE abab%%%%%` can still be folded using the prefix `abab%%%%` instead of `abab`, which matches the failing query sqllogic jobs on the PR head.

`calc_like_domain()` needs to derive the prefix from the normalized pattern variant, or collapse repeated trailing `%` there as well, before this can be approved.

File: tests/sqllogictests/suites/query/functions/02_0005_function_compare.test (hunk 2 above)
Comment (sundy-li) [reply tests/sqllogictests/suites/query/functions/02_0005_function_compare.test:165]: Fixed in 6830a9e53a. The runtime normalization already collapsed repeated trailing `%`, but `calc_like_domain()` was still folding against the raw pattern and stripping only one `%`. This commit switches planner/domain folding to the normalized `LikePattern::EndOfPercent(v)` prefix and adds a regression test in `src/query/functions/src/scalars/comparison.rs` so `abab%` and `abab%%%%%` fold identically.

**Comment by sundy-li** [comment]
Blocking issue on the current head: `normalize_simple_pattern()` now rewrites all-`%` patterns like `'%%%%%'` to `LikePattern::Constant(true)` in `src/query/expression/src/filter/like.rs:312`, but `calc_like_domain()` in `src/query/functions/src/scalars/comparison.rs:1008` still only recognizes `LikePattern::StartOfPercent(v) if v.is_empty()` as the always-true fold.

That means the zero-segment repeated-`%` case still does not fold like a single `'%'`. Runtime semantics are now normalized, but planner folding is not: `LIKE '%'` still drops the filter entirely (see `tests/sqllogictests/suites/mode/standalone/explain/explain_like.test:18`), while `LIKE '%%%%%'` falls through to `None` in `calc_like_domain()` and keeps the filter.

Since this PR is specifically about repeated-`%` LIKE folding, the `Constant(true)` branch needs the same `ALL_TRUE_DOMAIN` handling, and it should get a regression around `EXPLAIN ... LIKE '%%%%%'`, before I’d call it complete.

**Comment by sundy-li** [comment]
Updated the planner/domain fold for normalized all-`%` LIKE patterns. `calc_like_domain()` now treats `LikePattern::Constant(true)` the same as a single `%`, and the branch adds both a focused unit regression plus `EXPLAIN ... LIKE '%%%%%'` sqllogictest coverage.

**Comment by sundy-li** [comment]
Blocking issue in `src/query/functions/src/scalars/comparison.rs:1012`:

`LikePattern::Constant(true)` is not specific to the repeated-all-`%` case. `generate_like_pattern("")` already returns `Constant(true)` in `src/query/expression/src/filter/like.rs`, so this new `calc_like_domain` arm will also fold `LIKE ` into `ALL_TRUE_DOMAIN`.

That broadens optimizer behavior beyond the repeated-`%` fix. Please gate this on the original pattern being non-empty/all-`%`, or introduce a dedicated pattern variant for the all-wildcard case instead of reusing `Constant(true)`.

**Comment by sundy-li** [comment]
Scoped the repeated all-`%` fold in `calc_like_domain()` to non-empty all-wildcard patterns in `6e5eb97155`. Added `test_calc_like_domain_empty_pattern_does_not_fold_to_all_true` so the empty-pattern case no longer reuses the repeated-`%` optimizer path.
